version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
    # logging:
    #     driver: "json-file"
    #     options:
    #         max-file: 3
    #         max-size: 5m

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - loki
    volumes:
        - ./prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
    
