apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: time
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
      - name: time
        image: r0ach20/devops:latest
        ports:
        - containerPort: 5000
